# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Filtros e np.where()

A função `np.where()` é muito útil para fazer uma seleção condicional de elementos de um array. Por exemplo, em uma empresa, você pode querer identificar quais funcionários têm salários acima da média.


In [1]:
import numpy as np

# Salários dos funcionários
salarios = np.array([3000, 3500, 4000, 2000, 4500, 4000, 5000])

# Calcular a média salarial
media_salarial = np.mean(salarios)

print(media_salarial)

3714.285714285714


In [2]:
# Identificar funcionários com salários acima da média - respondendo as posicoes dentro doa array
funcionarios_acima_media = np.where(salarios > media_salarial)
#printando dentro do array salarios os salarios acima da média
print(funcionarios_acima_media)

(array([2, 4, 5, 6], dtype=int64),)


In [3]:
#filtrando direto do array, sem fazer o filtro where
print(salarios[funcionarios_acima_media])

[4000 4500 4000 5000]


In [4]:
print(salarios > media_salarial)

[False False  True False  True  True  True]


In [5]:
print(salarios[salarios > media_salarial])

[4000 4500 4000 5000]


In [6]:
print(salarios[salarios >= 4000]) 

[4000 4500 4000 5000]


In [7]:
#substituindo pelo texto os salarios acima da média e os salarios abaixo da media 
print(np.where(salarios > media_salarial, 'acima da média', 'abaixo da média'))


['abaixo da média' 'abaixo da média' 'acima da média' 'abaixo da média'
 'acima da média' 'acima da média' 'acima da média']


In [2]:
# dar bônus de 10% para os funcionários com salários abaixo da média, se não for abaixo da média continuar com o salario anterior
salarios_bonus = np.where(salarios < media_salarial, salarios * 1.1, salarios)
print(salarios)
print(salarios_bonus)

[3000 3500 4000 2000 4500 4000 5000]
[3300. 3850. 4000. 2200. 4500. 4000. 5000.]


In [9]:
# considerando novamente nossos salários originais
print(salarios)

[3000 3500 4000 2000 4500 4000 5000]


In [10]:
# filtrar os salários entre 3000 e 4500 com where
print(np.where((salarios >= 3000) & (salarios <= 4500)))

(array([0, 1, 2, 4, 5], dtype=int64),)


In [3]:
#Filtrando salarios maior  que 3000 e menor que 4500 e ajustando salarios maior que 3000 com 15% e mantendo salario maior que 4500
print(salarios)
salarios_ajustados = np.where((salarios >= 3000) & (salarios <= 4500), salarios * 1.05, salarios)
print(salarios_ajustados)


[3000 3500 4000 2000 4500 4000 5000]
[3150. 3675. 4200. 2000. 4725. 4200. 5000.]


In [4]:
# filtrar os salários abaixo de 3000 ou (or|) acima de 4500 com where
print(np.where((salarios_ajustados < 3000) | (salarios_ajustados > 4500))) 

(array([3, 4, 6]),)


In [13]:
#Filtrando salarios menor que 3000 ou acima de 4500 e ajustando salarios maior que 3000 com 10% e mantendo salario maior que 4500
salarios_ajustados = np.where((salarios_ajustados < 3000) | (salarios_ajustados > 4500), salarios_ajustados * 1.1, salarios_ajustados)
print(salarios_ajustados) 

[3150.  3675.  4200.  2200.  5197.5 4200.  5500. ]
